### PR TITLE
Add performance data and switch command line to use standard arguments

### PR DESCRIPTION
**Pull request by DerDakon**

### CODE REVIEW

**Comment by DerDakon** [comment]
ping?

**Comment by DerDakon** [comment]
ping?

**Comment by elecnix** [comment]
I'm no longer using this repo. Either you or @samukasmk should take over with your own forks.

**Comment by DerDakon** [comment]
Ok, thx for the hint, I'll redirect it to @samukasmk then.

**Comment by DerDakon** [comment]
Now merged to fork of @samukasmk.

**Pull request closed without merging**
